### ISSUE TITLE
Unused imports

### ISSUE THREAD

**Issue by hughdbrown** [madscheme/fastapi#3]
https://github.com/madscheme/fastapi/blob/fd72f0266454602a1e044516d014f093591f3e7f/data/init.py#L5-L6

```
init.py:5:30: F401 [*] `sqlite3.IntegrityError` imported but unused
init.py:6:19: F401 [*] `error.Missing` imported but unused
init.py:6:28: F401 [*] `error.Duplicate` imported but unused
```

**Comment by madscheme** [comment]
Dropped Missing and Duplicate. Keeping IntegrityError, which is used by other importers of init.
